# PostgreSQL configuration for DevHub
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: devhub_development
  username: devhub
  password: devhub
  host: localhost

test:
  <<: *default
  database: devhub_test
  username: devhub
  password: devhub
  host: localhost

production:
  <<: *default
  database: devhub_production
  username: devhub
  password: <%= ENV["DEVHUB_DATABASE_PASSWORD"] %>
  host: localhost